name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed rocknix_manager.py

      - name: Upload exe artefact
        uses: actions/upload-artifact@v3
        with:
          name: RocknixManager-Windows
          path: dist/*.exe
