name: Build Windows

on:
  push:
    tags:
      - 'v*' # Ativa quando você cria uma versão (ex: v1.0.4)

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write # Permissão extra direto no código

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed rocknix_manager.py

      - name: Check files (Debug)
        run: |
          ls dist/ # Isso vai listar o que tem na pasta dist no log do GitHub

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
