name: Build Windows

on:
  push:
    tags:
      - 'v*' # Isso fará o robô rodar toda vez que você criar uma tag (ex: v1.0.1)
  workflow_dispatch: # Isso permite que você rode o build manualmente se quiser

jobs:
  build-windows:
    runs-on: windows-latest
    permissions: # Garante que o robô tenha permissão para postar a release
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed rocknix_manager.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe # O PyInstaller coloca o exe na pasta 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
