name: Build Windows EXE

on:
  push:
    tags:
      - 'v*' # Dispara quando cria uma tag (ex: v7.6.1)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyqtdarktheme paramiko requests pyinstaller
        # Adicionei paramiko (para o seu SSH) e qdarktheme (para o tema)

      - name: Build
        run: |
          pyinstaller --onefile --windowed --name "RocknixManager" rocknix_manager.py

      - name: Publish Release
              shell: pwsh
        run: |
          if (Test-Path "dist/RocknixManager.exe") {
            Write-Host "Sucesso: O executável foi criado!"
            ls dist/
          } else {
            Write-Error "Erro: O PyInstaller não gerou o arquivo!"
            exit 1
          }
      - name: Publicar na Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/RocknixManager.exe
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
